def test(self):
    self.cur.execute("CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY, category text)")
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Narzędzia",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Meble",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Gospodarstwo domowe",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Ogród",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Urządzenia",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Gry wideo",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Książki, filmy i muzyka",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Torby i walizki",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Odzież damska i obuwie",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Odzież męska i obuwie",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Biżuteria i akcesoria",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Zdrowie i uroda",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Artykuły dla zwierząt domowych",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Dzieci",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Zabawki i gry",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Elektronika i komputery",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Telefony komórkowe",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Rowery",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Sztuka i rzemiosło",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Sport i aktywność na świeżym powietrzu",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Części samochodowe",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Instrumenty muzyczne",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Antyki i kolekcje",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Wyprzedaż garażowa",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Różne",))
    self.cur.execute("INSERT INTO categories VALUES (NULL, ?)", ("Pojazdy",))
    self.conn.commit()
